name: Build docker image and push to ECR
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Select Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Build docker image
        run: docker build .  -t ${{ secrets.AI_ENGINE_ECR }}:latest

      - name: Print Working directory
        run: pwd

      - name: Getting AWS Token
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 288761749700.dkr.ecr.eu-central-1.amazonaws.com

      - name: Push image to ECR
        run: docker push ${{ secrets.AI_ENGINE_ECR }}:latest
